package org.login;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class Login {
	public static void main(String[] args) throws InterruptedException {
		System.setProperty("webdriver.web.driver", "C:\\Users\\Nandhasrivaari S\\eclipse-workspace\\Flipkart\\Driver\\chromedriver.exe");
		WebDriver driver =new ChromeDriver();
		driver.get("https://adactinhotelapp.com/");
		WebElement login=driver.findElement(By.id("username"));
		login.sendKeys("Nandha23");
		WebElement pass=driver.findElement(By.name("password"));
		pass.sendKeys("Qwerty23@");
		Thread.sleep(5000);
		WebElement logi=driver.findElement(By.name("login"));
		logi.click();
		WebElement location=driver.findElement(By.name("location"));
		Select a=new Select(location);
		a.selectByValue("London");
		WebElement hotel=driver.findElement(By.name("hotels"));
		Select b=new Select(hotel);
		b.selectByValue("Hotel Hervey");
		WebElement room =driver.findElement(By.name("room_type"));
		Select c=new Select(room);
		c.selectByValue("Super Deluxe");
		WebElement type =driver.findElement(By.id("room_nos"));
		Select d=new Select(type);
		d.selectByIndex(4);
		WebElement per=driver.findElement(By.name("adult_room"));
		Select e1=new Select(per);
		e1.selectByValue("3");
		WebElement children=driver.findElement(By.name("child_room"));
		Select f=new Select(children);
		f.selectByValue("3");
		WebElement search=driver.findElement(By.name("Submit"));
		search.click();
		Thread.sleep(5000);
		WebElement select=driver.findElement(By.name("radiobutton_0"));
		select.click();
		WebElement contin=driver.findElement(By.name("continue"));
		contin.click();
		Thread.sleep(5000);
		WebElement name=driver.findElement(By.name("first_name"));
		name.sendKeys("NANDHA");
		WebElement last=driver.findElement(By.name("last_name"));
		last.sendKeys("S");
		WebElement billing=driver.findElement(By.name("address"));
		billing.sendKeys("XXX,YYY,ZZZ");
		WebElement card=driver.findElement(By.name("cc_num"));
		card.sendKeys("5467898908312490");
		WebElement credit=driver.findElement(By.name("cc_type"));
		Select g =new Select(credit);
		g.selectByValue("VISA");
		WebElement date=driver.findElement(By.name("cc_exp_month"));
		Select h =new Select(date);
		h.selectByValue("6");
		WebElement year=driver.findElement(By.name("cc_exp_year"));
		Select i =new Select(year);
		i.selectByValue("2026");
		WebElement cvv=driver.findElement(By.name("cc_cvv"));
		cvv.sendKeys("678");
		WebElement touch=driver.findElement(By.name("book_now"));
		touch.click();
		Thread.sleep(5000);
		WebElement iter=driver.findElement(By.id("my_itinerary"));
		iter.click();
		WebElement order=driver.findElement(By.name("order_id_text"));
		order.sendKeys("Y6IBS9NV1L");
		Thread.sleep(2000);
		WebElement go=driver.findElement(By.name("search_hotel_id"));
		go.click();
		Thread.sleep(2000);
		WebElement out=driver.findElement(By.name("logout"));
		out.click();
		Thread.sleep(5000);
		driver.manage().window().minimize();  
	}
}
